source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SimpleCalculator_Example', :exclusive => true do
  pod "SimpleCalculator", :path => "../"
end

target 'SimpleCalculator_Tests', :exclusive => true do
  pod "SimpleCalculator", :path => "../"

  
end
